Fix one critical bug
xphoenix/afina pull request #45
Opened 2019-04-02 08:29 UTC by sergey-protserov

2019-04-02 08:33 UTC, xphoenix requested changes
Если логирования не хватало для того, чтобы найти баг, то надо логирование добавить. Так что пожалуйста, пройдись по коду и добавь логирование ошибок epoll там, где его нет.

2019-04-02 08:50 UTC, sergey-protserov commented
Если я правильно понял, теперь с этим pull-request ассоциируются два коммита, второй из которых добавляет отладочные сообщения.

2019-04-02 18:24 UTC, sergey-protserov commented
Update

2019-04-03 06:51 UTC, xphoenix approved these changes

2019-04-03 06:51 UTC, merged